name: Publish the mod

on:
  release:
    types: [published]


jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Build with Gradle
        run: ./gradlew build
        env:
          DISABLE_PROPERTIES_UPDATE: true

      - name: Upload to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
